# Generated by Django 5.2.3 on 2025-07-15 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0003_orden_direccion_envio'),
        ('promo_codigo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='promo_codigo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promo_codigo.promocodigo'),
        ),
    ]
